services:
  proxy:
    build:
      context: .
      pull: true
    pull_policy: build
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./captures:/wd/captures
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
