"""neplocal - Decode the local binary protocol used by NEP solar microinverters."""

from .protocol import (
    AC_VOLTAGE_OFFSET,
    AC_VOLTAGE_SCALE,
    CLOUD_HOST,
    CLOUD_PATH,
    CMD_TELEMETRY,
    CURRENT_SCALE,
    ENERGY_SCALE,
    FREQUENCY_SCALE,
    MAGIC,
    MODULE_SIZE,
    POWER_SCALE,
    TEMPERATURE_OFFSET,
    TEMPERATURE_SCALE,
    VOLTAGE_SCALE,
    ModuleReading,
    TelemetryFrame,
    count_modules,
    decode_frame,
    verify_checksum,
)

__all__ = [
    "MAGIC",
    "CMD_TELEMETRY",
    "CLOUD_HOST",
    "CLOUD_PATH",
    "VOLTAGE_SCALE",
    "CURRENT_SCALE",
    "POWER_SCALE",
    "ENERGY_SCALE",
    "FREQUENCY_SCALE",
    "AC_VOLTAGE_SCALE",
    "AC_VOLTAGE_OFFSET",
    "TEMPERATURE_SCALE",
    "TEMPERATURE_OFFSET",
    "MODULE_SIZE",
    "TelemetryFrame",
    "ModuleReading",
    "decode_frame",
    "verify_checksum",
    "count_modules",
]
